name: kintaikei_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  intl: ^0.18.1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  syncfusion_localizations: ^23.2.7
  syncfusion_flutter_calendar: ^23.2.7
  modal_bottom_sheet: ^2.1.2
  flutter_spinkit: ^5.2.1
  introduction_screen: ^3.1.14
  home_widget: ^0.5.0
  alert_banner: ^1.0.1
  package_info_plus: ^7.0.0
  common_utils: ^2.1.0
  board_datetime_picker: ^1.4.0

  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  firebase_messaging: ^14.7.15
  flutter_local_notifications: ^16.3.2

dependency_overrides:
  modal_bottom_sheet: ^3.0.0-pre

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: SourceHanSansJP-Bold
      fonts:
        - asset: assets/fonts/SourceHanSansJP-Bold.otf
    - family: SourceHanSansJP-Regular
      fonts:
        - asset: assets/fonts/SourceHanSansJP-Regular.otf